name: google_geofence_helper_example
description: Example app for the google_geofence_helper

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_geofence_helper:
    path: ../
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 